AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String 
  myUsername:
    Description: Any username
    Type: String 
  myPassword:
    Description: A password with at least 8 characters
    Type: String  
Resources:
  # Choose a name of your choice
  myDBSubnetGroup11:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "Subnets to use for the DB"
      DBSubnetGroupName: "Subnet Group"
      # Replace these IDs, as applicable to you
      SubnetIds:
      - subnet-0cf06c30133e1e129
      - subnet-046532a60313c042f
  # Choose a name of your choice    
  MyDB: 
    Type: "AWS::RDS::DBInstance"
    Properties: 
      # Replace this ID, as applicable to you. I have used the default SG. 
      VPCSecurityGroups: [sg-0cf82774034f287ff]
      PubliclyAccessible: false
      MultiAZ: false
      AllocatedStorage: 20
      DBInstanceClass: db.t2.small
      Engine: "mysql"
      MasterUsername: !Sub "${myUsername}"
      MasterUserPassword: !Sub "${myPassword}"
      DBSubnetGroupName: !Ref myDBSubnetGroup11
      Tags: 
        - 
          Key: "Name"
          Value: !Sub "${EnvironmentName} MySQL RDS"
    DeletionPolicy: "Retain"